spf13/viper

- README.md
- viper.go
- viper_test.go
Use case is replacing `-` in my command line/viper keys with `_` when retrieving env vars.
```
viper.AutomaticEnv()
viper.SetEnvKeyReplacer(strings.NewReplacer("-", "_"))
```
> Support rewriting envvar keys

- README.md
* Change the order to "JSON, TOML and YAML" because that is
the order that Viper attempts to find the config file,
as listed in SupportedExts string array
* Rename "Indexes" to "Taxonomies" (re: Hugo)
* GitHub now forces https, so update GitHub URLs accordingly
* Add links to Wikipedia pages about Viper and Cobra Commander
in case the users do not know the G.I. Joe reference
* Other minor copyediting
> Minor revisions to README.md

- viper.go
Viper should not be searching for config.{json,toml,yaml,yml}
in the directory where the `hugo` executable binary is located,
i.e. do not try to look for e.g. $GOPATH/bin/config.toml or
/usr/local/bin/config.toml
* * *
Hi @spf13,
When I was running `$GOPATH/bin/hugo` trying to figure out in what order Viper tries to load the config file (json, toml or yaml), I saw these debug messages:
```
DEBUG: 2015/01/22 Searching for config in  /home/foka/go/bin
DEBUG: 2015/01/22 Checking for /home/foka/go/bin/config.json
DEBUG: 2015/01/22 Checking for /home/foka/go/bin/config.toml
DEBUG: 2015/01/22 Checking for /home/foka/go/bin/config.yaml
DEBUG: 2015/01/22 Checking for /home/foka/go/bin/config.yml
DEBUG: 2015/01/22 Searching for config in  /work/web/anthonyfok.org
DEBUG: 2015/01/22 Checking for …
```
> Avoid searching for config file in executable's path

- util.go
- viper.go
Although neither "insensativise" nor "insensitivise" appears in the dictionary, a quick Google search reveals 0 search result for the former, and about 135 results (+ 395 results if you count "insens**i**tivi**z**e") for the latter, and that it relates to "case insens**i**tive", hence the pull request.
Sorry, this is really really unimportant, so please feel free to ignore it.  <grin, duck, run>
> :%s/insensativiseMap/insensitiviseMap/g

- util.go
- viper.go
- viper_test.go
Added support for properties file format configs (via the magiconair/properties) library
> 59 - add properties file support to viper

- viper.go
This patch fixes a bug where the function `AllKeys()` did not include the keys for bound flags and environment variables.
> AllKeys() now includes bound flag and env var keys

- README.md
- viper.go
- viper_test.go
Suppose I have a component which accepts a Viper object as config when it's initialized. Now I embed the config information of the component in the main config. But the component does not know where the root of its config is. In this case, with the Sub() function, the main program can extract exactly the sub-tree for this component and transfer the sub-tree to the component.
> Add Sub() for Viper, which returns a branch of a Viper instance.

- viper.go
- viper_test.go
Sometime Get()returns type map[interface{}]interface{}. This patch is able to handle it as well as map[string]interface{}.
> Handle the case Get() returns map[interface{}]interface{}

- viper.go
- viper_test.go
This functions protects from configs that might have unused or mistyped fields when unmarshalling into a struct. The relevant test passes.
> Adding an Unmarshal Function that errors when a field in the conf is not present in the destination struct

- util.go
This patch updates the package used for parsing TOML content from `github.com/BurntSushi/toml` to `github.com/pelletier/go-toml` as the latter uses a more accepted OSS license (MIT), enabling the inclusion of Viper or projects that depend on Viper in projects that have licensing requirements incongruent with the license of the previous TOML package.
This patch replaces the PR #208 after discussing the matter with @spf13 and deciding to update the TOML parser instead of making TOML build-optional.
> TOML Library Licensing

- viper.go
- viper_test.go
I stumbled over this when trying to merge multiple configs.
```
viper.SetConfigName("default")
err := viper.MergeInConfig()
```
which caches file path resolvemenet in `v.configFile`
and then
```
viper.SetConfigName("prod")
err := viper.MergeInConfig()
```
which reuses `v.configFile` without updating it accordingly to the new name.
See https://github.com/spf13/viper/blob/c1ccc378a054ea8d4e38d8c67f6938d4760b53dd/viper.go#L1240
> Changing config name should also reset file name cache

- util.go
- viper.go
Hi there,
I was in the process of implementing some unit tests for a config write feature (as described in https://github.com/spf13/viper/pull/153), and noticed that Viper does not currently use the Afero filesystem framework.
It would be nice if Viper used the Afero backend as it would allow for mock filesystems in unit tests.
Let me know if I have missed anything or if something should be changed!
> Add support for Afero filesystems

- .travis.yml
Since Hugo is such a heavy user of Viper, this patch adds an `after_success` section to the Travis-CI build in order to validate the Viper commit by attempting to build Hugo and executing `hugo -s docs`.
This patch handles issue #222 and is in response to the need for additional testing discovered due to PRs #217 and #228.
> Add Hugo CI Step to Validate Viper

- viper.go
With some extra trace log formatting changes thrown into the mix.
Fixes #112
> Fix retrieval of pflag stringSlice

- viper.go
- viper_test.go
Just add DecodeHook to DecoderConfig.
Allows to unmarshal into struct with time.Duration fields:
```
package main
import (
"bytes"
"fmt"
"github.com/spf13/viper"
"time"
)
type Config struct {
Timeout time.Duration
String  string
}
func main() {
var cfg Config
viper.SetConfigType("yaml")
var yamlExample = []byte(`
Timeout: 200ms
String: it works!
`)
viper.ReadConfig(bytes.NewBuffer(yamlExample))
viper.Unmarshal(&cfg)
// {Timeout:200ms String:it works!}
fmt.Printf("%+v\n", cfg)
}
```
> Issue-105 Support time.Duration in viper.Unmarshal

- .gitignore
- viper.go
- viper_test.go
Also avoid doing a strings.Split in the Get common case.
Any TRACE statements in these hot paths must be totally turned off when not testing.
```
benchmark                     old ns/op     new ns/op     delta
BenchmarkGetBool-4            4090          409           -90.00%
BenchmarkGetBoolFromMap-4     6.33          6.28          -0.79%
benchmark                     old allocs     new allocs     delta
BenchmarkGetBool-4            6              3              -50.00%
BenchmarkGetBoolFromMap-4     0              0              +0.00%
benchmark                     old bytes     new bytes     delta
BenchmarkGetBool-4            129           33            -74.42%
BenchmarkGetBoolFromMap-4     0             0             +0.00%
```
Fixes #242
> Remove expensive TRACE logging in find

- README.md
- overrides_test.go
- util.go
- viper.go
- viper_test.go
This PR should fix #168 and #190, among others, by updating the `Set*()` functions so that they change “deep” values in the configuration maps.
**Not ready for merge**: no code yet, only unit tests in file `overrides_test.go` (corresponding to the cases discussed in #168), to make sure we agree on the final behavior.
Please comment if you wish to change anything.
> Nested maps

- README.md
There was annoying space between space between projects and badges. This PR fixes it
> Fix space between Go projects and badges

- README.md
`IsChanged` is actually named `HasChanged`, and the examples were missing function return declarations, so you couldn't just copy/paste it.
> Correct FlagValue interface examples in Readme

- viper.go
- viper_test.go
Currently, when I run a Viper-enabled application without a configuration file, expecting it to just use the default values, I see a slightly unintuitive error: `Unsupported Config Type ""`. When I *write* an application with Viper, I have no way to distinguish between configuration file errors and users who have chosen not to write an explicit config file. Although `findConfigFile()` can return a `ConfigFileNotFoundError`, some of its callers (e.g., `getConfigFile()`) silently drop the error, resulting in lots of `""` strings with no explanation. Code like `ReadInConfig()` must then re-construct the error without information about why it occurred, so "there is no config file" is conflated with "the config file is not a valid format".
This patch changes `getConfigFile()` to propagate the …
> Allow errors to propagate through getConfigFile()

- util.go
- viper.go
- viper_test.go
This follows PR #253, which closed Issue #249 induced by PR #195.
It generalizes to nested keys the improvement from PR #253 which consists in assuming that all keys are lower-cased, thus allowing to search for values by writing
```golang
val = m[key]
```
instead of
```golang
for k, v := range m {
if strings.ToLower(k) == strings.ToLower(key) {
val = v
}
}
```
This induces a huge performance gain.
Function `insensitiviseMap()` was also fixed (it did not recurse correctly through the inner maps).
@bep my performance tests show no performance loss (and even very little gain) from your version, can I let you benchmark on your hardware to make sure I didn't remove anything essential (it should be fine, but let's double-check this time...)?
If that's OK for you, I think this would be a more …
> Increase performance of nested keys search

- viper.go
- viper_test.go
Bug fixed in `AllKeys()` by doing an explicit cast of `v.env` to a `map[string]interface{}`.
This will in turn repair `AllSettings()` and `Unmarshal()`, which also ignored environment values added manually.
Fixes issue raised in [this comment](https://github.com/spf13/viper/pull/195#issuecomment-255517435) in PR #195, and mentioned at the end of Issue #188.
> Fixed AllKeys() to include env values added with BindEnv()

- viper.go
- viper_test.go
* **Fixed**: UnsupportedConfigError is returned if config file is not found
Swap getConfigFile and getConfigType call
Add a unit test
> Fix MergeInConfig error return

- viper.go
If the user creates a invalid config file while watching for config
changes, the previous, valid config is not retained.  This commit only
overwrites the running config if unmarshalling was successful.
Updates spf13/hugo#2603
> Only save config on success in ReadInConfig

- remote/remote.go
- viper.go
This fix would avoid that while using the RemoteWatch-feature go-routines are started which never get stopped what causing a mem-leak (described here)
> Avoid the start of go-routines which are never get stopped (Description Issue #312)

- viper.go
- viper_test.go
The use case arose when using UnmarshalKey on structs that contain nested structs that contain a time.Duration it would throw a message like:
`* '[0].Nested.Delay' expected type 'time.Duration', got unconvertible type 'string'`
This PR fixes the handling of time.Duration objects and adds a test for it.
> Fix UnmarshalKey handling of time.Duration

- viper.go
- viper_test.go
Added a code handling a pflag.StringSlice values. Also tested most cases.
It fixes #200.
Similar to: https://github.com/spf13/viper/pull/244
> Properly handle string slice values

- viper.go
There is no need to assert variables which already have appropriate
type.
```
name              old time/op    new time/op    delta
GetBool-4            554ns ± 3%     493ns ± 8%  -10.86%  (p=0.000 n=14+15)
Get-4                484ns ± 4%     414ns ± 7%  -14.37%  (p=0.000 n=14+15)
GetBoolFromMap-4    8.38ns ± 6%    7.83ns ± 7%   -6.59%  (p=0.000 n=15+15)
name              old alloc/op   new alloc/op   delta
GetBool-4            65.0B ± 0%     64.0B ± 0%   -1.54%  (p=0.000 n=15+15)
Get-4                64.0B ± 0%     64.0B ± 0%     ~     (all equal)
GetBoolFromMap-4     0.00B          0.00B          ~     (all equal)
name              old allocs/op  new allocs/op  delta
GetBool-4             5.00 ± 0%      4.00 ± 0%  -20.00%  (p=0.000 n=15+15)
Get-4                 5.00 ± 0%      4.00 ± 0% …
```
> Prevent redundant type assertion in Get

- README.md
The existing example code for using flags does not include a complete usable snippet that you can paste into an existing project and easily see how to adapt it to use Viper.   This is a relatively minor change, but merging it in would make it simpler for the next person who comes along (like I have, multiple times) looking for a simple snippet to drop in that clearly shows how to integrate existing flags in your project with Viper.
> Improve documentation for flags

- README.md
- viper_test.go
Change `SetEnvReplacer` to `SetEnvKeyReplacer`
> Fix incorrect name of function in README.md

- util.go
- viper.go
This allows it to work with non-default instances of Viper as you would expect. `searchInPath` then passes it's own instance of `fs`.
Signed-off-by: Jeff Lindsay <progrium@gmail.com>
> Allow exists util function to take afero.Fs

- README.md
This is a useful usecase, which is not documented.
Maybe this could be brought into viper itself with the same format string that are currently supported by `WriteConfigAs()` and friends. This could also simplify the `v.marshalWriter()` function by removing error handling duplication.
> Add example of marshalling to string

- viper.go
- viper_test.go
Hi
I recently ran into an issue when using `viper.Unmarshal` in-conjunction with Environment variables. I wished to pass a `json` object as a value to an Environment variable for user names and passwords that I didn't want to write to a config file, for example:
```
export MY_CONFIG_VAL={\"foo\":\"bar\",\"fizz\":\"buzz\"}
```
Whilst `viper.GetStringMapString` would work perfectly, `Unmarshal` would fail with: 
```
* 'my_config_val' expected a map, got 'string'
```
I did some digging and saw this was failing in `mapstructure`. I saw it supported custom `DecodeHook` functions so I could write my own function to parse the value correctly, however `viper` does not support the ability to customise the `mapstructure.DecoderConfig`.
So this PR adds the following (it's worth noting this is 100% …
> Support customising mapstructure.DecoderConfig for Unmarshal

- viper.go
- viper_test.go
Hi,
in Debian, we've discovered an overflow error on 32 bit architectures:
https://bugs.debian.org/860678
These two commits enable all tests to pass on 32 and 64 bit architectures.
> Fix overflow error on 32 bit architectures

- .gitignore
- viper.go
- viper_test.go
Support override of symlink to config file
Include tests for WatchConfig of regular files, as well
as config file which links to a folder which is itself a
link to another folder in the same "watch dir" (the way
Kubernetes exposes config files from ConfigMaps mounted
on a volume in a Pod)
Also:
- Add synchronization with WaitGroup to ensure that the WatchConfig
is properly started before returning
- Remove the watcher when the Config file is removed.
Fixes #284
Signed-off-by: Xavier Coulon <xcoulon@redhat.com>
> WatchConfig and Kubernetes (#284)

- util.go
- viper.go
Switching jww from jwalterweatherman to jWalterWeatherman,
`vgo` breaks otherwise.
```
vgo: import "github.com/elastic/<snipped>" ->
import "github.com/elastic/<snipped>/cmd" ->
import "github.com/spf13/viper" ->
import "github.com/spf13/jwalterweatherman": module path of repo is github.com/spf13/jWalterWeatherman, not github.com/spf13/jwalterweatherman (wrong case)
```
> Cater for case-sensitive dependencies

- README.md
- viper.go
- viper_test.go
Empty environment variables are perfectly valid values.
Fortunately Go provides a way to check whether an env var
is empty or not set.
Fixes #317 
Resubmitted #429
> Lookup environment variables instead of checking if the value is empty

- viper_test.go
Highlighted and fixed a small bug in `TestBindPFlagsStringSlice()` (introduced in recently merged PR #296).
~While I was at it, moved all the flag-related tests from `viper_test.go` to the existing `flags_test.go` for consistency.~
See individual commits for details, they should be clear enough.
> Tests for flags handling improved

- viper.go
> Remove superflous insensitiviseMaps in Unmarshal methods

- viper.go
This allows users to set the file permissions that Viper uses for the config file.
fixes: #480
> Add API for setting file permissions

- README.md
The indentation seemed messed up and didn't read well. This change fixes it.
> Fix indentation for yamlStringSettings

- README.md
This is used to clarify more on BindEnv to keep newcomers from confusion.
> BindEnv details specified. Now less confusion.

- README.md
Previously, this PR contained a solution to the problem pointed out in issue #1 (namely a `ReadInConfigIfExists()` function. But I think that the solution shown in the comments of #1 is probably a better approach, so I've chosen to document that approach instead.
cc @sagikazarmark
> Provide documentation for ignoring "config file not found" error

- README.md
- viper.go
- viper_test.go
Kinda follow up this PR : https://github.com/spf13/viper/pull/637
Adds a simple `GetIntSlice` methods that enables parsing int slices from config the same way `GetStringSlice` works.
> Add GetIntSlice helper method

- viper.go
Defering can cause trouble because we're writing to the file outside the function
where the defering is registered, calling f.Sync() ensures that bytes are flushed
to disk even is Close() is called too soon.
Ref #542
> Fixed missing f.Close() in writeConfig()

- viper.go
If the config file does not exist and the force flag is not set,
OpenFile would not use O_CREATE flag, causing viper to fail with
error "File not exist" and to not create the config file.
This patch changes the behavior of writeConfig() so that if force is set
to false, OpenFile will use O_EXCL flag, thus failing if the file
already exists or creating a new file otherwise.
Signed-off-by: Rodrigo Chiossi <rodrigo.chiossi@intel.com>
> Fix SafeWriteConfig

- viper.go
- viper_test.go
Fixes #324 
Includes fix #669
- Replaced the use of `strings.Split` with a method that takes a fully qualified key and returns a list of valid map keys which may include dots in them.
- Reformatted test objects to improve readability and Git change diffing.
- Added key containing dot to yaml test.
> Unmarshal keys containing dots

- remote/remote.go
A `:=` assignment inside an if-block caused two `error` variables to be shadowed. Here is a fix.
> Fix Dropped Errors

- viper.go
- viper_test.go
This PR reverts #673 because it introduced a breaking change.
Fixes #764
> Revert unmarshal keys containing dots

- go.mod
- go.sum
Make sure we're not vulnerable to CVE-2019-11253.
See https://github.com/kubernetes/kubernetes/issues/83253
> Updates YAML to v2.2.4

- README.md
- viper.go
- viper_test.go
Support config files with no extension.
Closes: spf13/viper#390
Closes: spf13/viper#336
Similar to https://github.com/spf13/viper/pull/357/files which appears to have been forgotten. 
Difference is: attempt a no extension right away instead of messing with the extension append and iterating through the extensions.
> Support config files with no extensions

- viper.go
- viper_test.go
Added flexibility to `find()` function with an extra boolean argument, so that it can be used both by `Get()` (to retrieve a value, including flag's default) and `IsSet()` (whether the key is set, ignoring flag's default).
Fixes #276 
Fixes #580
(+ added some tests to enforce this behavior)
> IsSet() returns false when flags are not set

- viper.go
- viper_test.go
> Add INI support

- README.md
- viper.go
- viper_test.go
This PR adds a new constructor for Viper and a functional option for the key delimiter. This is an initial solution for supporting keys containing the key delimiter.
For the mid-term, I would probably add back the feature reverted in #771 (and fixed in #766) with a feature flag `v.AllowDelimiterInKey` defaulting to false. That changes the behavior of Viper though (see https://github.com/spf13/viper/pull/766#issuecomment-532644550) which is why we need the flag, defaulting to false.
cc @inkychris @mschneider82
> Add key delimiter setter

- viper.go
There is no helper method for UnmarshalExact which calls the
corresponding method on the global viper instance.
> Add global UnmarshalExact method

- README.md
This issue keeps coming up (#797 #820 #822) so I thought it might make sense to document it.
> Add documentation about unmarshaling into embedded structs

- README.md
- viper.go
- viper_test.go
This PR addresses #818 
cc @andig
> Extensionless files only allowed when config type is set

- viper.go
- viper_test.go
The suppport introduced for files with no file extension is only partial as trying to save the config file would fail with `<file name> equires valid extensio`
This adds support to saving such files
> Add support to save file with no extension

- go.mod
- go.sum
This dependency bump is in reference to #898 and https://github.com/spf13/cobra/issues/1091
Bumps to the latest patch version of `gorilla/websocket` 1.4
Let me know if there are questions!
> Update gorilla dependency

- viper.go
While new Viper with ini file and call method v.WriteConfig or v.WriteConfigAs, the method will return err "interface conversion: interface {} is nil, not string"
> fix bug while saving ini file

- viper.go
- viper_test.go
As viper parses pflag values as strings, string to string values weren't being handled correctly . Fixes #608 .
> Fix: Getting the value of a StringToString pflag

- viper.go
Checking for `nil` error doesn't make a scene, since we return it (or `nil`).
All `func (v *VIper) Unmarshal*` methods affected.
> Skipping error != nil checks in favor of the fast return.

- util.go
- util_test.go
I've created a new PR to address the path expansion issue first reported by @biochimia in #495.
This PR simply adds requested changes to speed things along. CC: @sagikazarmark 
Fixes #495
> Fix abs pathify

- viper.go
- viper_test.go
I ran into a nasty problem while changing a Cobra command from `flag` to a `persistentFlag`. The old code to bind the flag to viper did not error out after the new change, and allowed me to bind a wrapped empty flag. (details below)
This PR adds a check to make sure the passed in flag value is not `nil`. Without this check, a `nil` value gets wrapped in a new `pflagValue`, and later nil checks do not detect the problem.
More details: 
```
cmd.Flags().StringVarP(&myConfig, "myFlagName", ...
...
if err := viper.BindPFlag("myViperKey", cmd.Flags().Lookup("myFlagName")); err != nil { ...
```
When I changed the Cobra code to use a Persistent flag (as shown below), the viper.Bind call didn't notice any issue. The problem was the cmd.Flags.Lookup() was now returning nil. I needed to use …
> BindPFlag() detect nil flag before wrapping in pflagValue

- README.md
- viper.go
- viper_test.go
This change modifies BindEnv to permit a list of environment variable
names in order to support multiple env. vars. for the same config key.
When this form is used, env. keys take precedence in the written order.
Closes #971
> Allow BindEnv to register multiple environment variables.

- .github/workflows/ci.yml
- README.md
- internal/testutil/env.go
- util_test.go
- viper_test.go
Instead of using `os.Setenv` everywhere, use a helper function that resets the original value.
The implementation is based on https://github.com/frankban/quicktest/blob/577841610793d24f99e31cc2c0ef3a541fefd7c7/patch.go#L34-L64
> Add setenv helper for tests

- README.md
- viper.go
- viper_test.go
Hi,
I added support for accessing values within a slice as mentioned in #196. For example, if we have a config file which is structured like this:
```json
{
"server_name": "example.com",
"interfaces": [
{
"interface": "192.168.1.1",
"port": 80
},
{
"interface": "127.0.0.1",
"port": 8080
}
]
}
```
We can now get the second interface config like so `viper.Get("interfaces.1")` or specifically the port like so `viper.GetInt("interfaces.1.port")`
I have chosen to implement the index numbers like path parts since it is way more difficult to try to parse the go like syntax `viper.Get("interfaces[1]")` and still respect the other functionality like shadowing checks.
> Added support for accessing slices

- README.md
It's a bit, but can save someone's minutes.
> Fix typo of viper variable name

- .github/workflows/wasm.yml
- viper.go
- watch.go
- watch_wasm.go
fsnotify is not available on WASM,
so config watching is not going to work.
Fixes #1071
> Make sure Viper compiles on WASM

- viper.go
- viper_test.go
When merging a key where the target value is nil, the type of the target and source do not match. What currently happens is an error is logged and the key is skipped.
I have changed it so that it does the same thing as when the target key is missing: copy the source value to the target.
Fixes #1134
> Fix merging a key into a nil target

- README.md
I apologize for my rude pr on modify readme
I think it is better to use %w in fmt.Errorf instead of %s
[go error doc](https://golang.org/pkg/errors/)
> update %s to %w

- internal/encoding/decoder.go
- internal/encoding/decoder_test.go
- internal/encoding/encoder.go
- internal/encoding/encoder_test.go
- internal/encoding/error.go
- internal/encoding/hcl/codec.go
- internal/encoding/json/codec.go
- internal/encoding/toml/codec.go
- internal/encoding/yaml/codec.go
- viper.go
This PR adds an encoding layer to Viper, separating direct calls to encoding libraries to different packages and ultimately moving out most of the logic from the main Viper package.
The package implements the proposal from #888 with the exception of moving them out from the module to preserve backwards compatibility. That cannot happen in the v1 branch as it would be a breaking change, but introducing an encoding layer this way allows us to move things out of the module easily in the future.
Although this is a sane proposal and I believe it's the way forward, the abstraction is not perfect and we can already see some shortcomings:
- TOML does not support `map[string]interface{}` well (compared to JSON and YAML anyway), so it contains some conditional logic specific to that type.
- Many …
> New encoding layer

- viper.go
- viper_test.go
Fixes https://github.com/spf13/viper/issues/884
`InConfig` starts to process paths instead of treating them strictly as keys to the `v.config` map
> fix: made `InConfig` process paths correctly

- util.go
Hi,
@sagikazarmark I created a fix for #1062 please review it.
Thx
Fixes #1062
> Improve variable expansion in AddConfigPath

- viper.go
- viper_test.go
> Fix cannot write hidden file without extension

- internal/encoding/decoder.go
- internal/encoding/decoder_test.go
- internal/encoding/dotenv/codec.go
- internal/encoding/dotenv/codec_test.go
- internal/encoding/dotenv/map_utils.go
- internal/encoding/encoder.go
- internal/encoding/encoder_test.go
- internal/encoding/hcl/codec.go
- internal/encoding/hcl/codec_test.go
- internal/encoding/ini/codec.go
- internal/encoding/ini/codec_test.go
- internal/encoding/ini/map_utils.go
- internal/encoding/javaproperties/codec.go
- internal/encoding/javaproperties/codec_test.go
- internal/encoding/javaproperties/map_utils.go
- internal/encoding/json/codec.go
- internal/encoding/json/codec_test.go
- internal/encoding/toml/codec.go
- internal/encoding/toml/codec_test.go
- internal/encoding/yaml/codec.go
- internal/encoding/yaml/codec_test.go
- viper.go
This is an attempt to further improve the encoding layer specified in #888 and introduced in #986.
Major changes introduced by this PR:
- Encoder/Decoder interfaces now accept `map[string]interface{}` instead of just `interface{}`. The rationale behind that change is that the encoding library is supposed to be used with Viper (it's not a generic library), so it's okay to make the interface Viper specific.
- Two additional codec implementations:
- INI
- Java properties
- Encoder/decoder registries are now instantiated per Viper instance. It's required for some codecs (INI, Java props)
The PR also adds some basic tests to the existing encoder implementations.
A couple notes and concerns regarding this change:
Both INI and Java properties require the key delimiter to do some key mutation …
> Improve encoding layer

- viper.go
- viper_test.go
This fixes the problem that appears when your base config has values with different type than the override, which is valid use case.
Fixes #1142
> Allow merging configs with different types of leaf values

- .github/workflows/ci.yml
- README.md
Underlying dependencies no longer compile on Go 1.14
> Drop Go 1.14 support

- viper.go
Adds in a MustBindEnv function which will panic if BindEnv fails.
> Add MustBindEnv

- viper.go
The logger interface uses k,v pairs, but it was being called with a
format string, here.
Changed to use k,v pairs.
I didn't find any other instances of this problem.
> chore: fix Error log calls in mergeMaps

- .github/workflows/ci.yaml
- internal/encoding/toml/codec.go
- internal/encoding/toml/codec2.go
- internal/encoding/toml/codec2_test.go
- internal/encoding/toml/codec_test.go
With this change TOML 3 library will become the default. The old version can be used by adding viper_toml1 to the list of build tags.
> Make TOML 2 the default

- README.md
Fix to example code, which fails static checks related to acceptable formats of error strings if used.
> Fix go-staticcheck failures (ST1005)

- README.md
use `jsonc` instead of `json` to improve readability
> Use jsonc in markdown codeblocks for better readability

- util.go
- viper_test.go
> Recurse into arrays when converting keys to lowercase

- viper.go
- viper_test.go
We have encountered numerous places where it is convenient to have viper return a `uint16` value, especially in combination with the new `netip` package  that represents a port correctly as `uint16` rather than just an `int`. cobra already supports this, but we need a conversion from the existing `GetUint` method in viper.
> Adds support for uint16 with `GetUint16`

- viper.go
One might want to write the debug information somewhere other than
Stdout. This patch adss a DebugTo function and method, that accepts
an io.Writer. It changes the original Debug implementation to call
this new function with a default of os.Stdout, which maintains
backward compatibility.
Signed-off-by: Brad P. Crochet <brad@redhat.com>
> Add a DebugTo convenience funtion

- .github/workflows/ci.yaml
- README.md
> Drop support for Go 1.15

- viper.go
> Fsnotify improvements

- viper.go
Added a small description of the WatchConfig().
So that you can understand in the ide why you could use it.
> Add DocBlock to WatchConfig

- viper.go
- viper_test.go
this fixes: https://github.com/spf13/viper/issues/1497
> fix: time.Duration slice type conversion

- viper.go
- viper_test.go
This PR fixes two issues with Sub():
-    Options were not copied from parent (e.g, automaticEnvApplied).
-   Environment variable names were wrong: Sub("x").Sub("y").Get("z") should look up env var x.y.z but was instead looking up z
Fixes https://github.com/spf13/viper/issues/745
Fixes https://github.com/spf13/viper/issues/507
> Sub parent inheritance

- .github/workflows/ci.yaml
- .golangci.yaml
- Makefile
- viper_test.go
> ci: add Go 1.20 to build matrix

- viper.go
> add:viper: allow to disable internal log messages

- util.go
- viper.go
- viper_test.go
Currently, viper errors cannot be unwrapped and hence do not give access to inner errors. Together with e.g. https://github.com/go-yaml/yaml/pull/760 this could be used to get access to the source file position producing the error.
> Allow ConfigParseError to unwrap

- .github/workflows/ci.yaml
- `actions/setup-go` provides module-caching feature for dependencies [from v4](https://github.com/actions/setup-go/releases/tag/v4.0.0).
- However, the cache is not working correctly in the current job configuration.
- One of the example job result is https://github.com/spf13/viper/actions/runs/5120214703 with the warning message `Restore cache failed: Dependencies file is not found in /home/runner/work/viper/viper. Supported file pattern: go.sum`. 
- [By default, the caching function of `actions/setup-go` depends on the contents of the go.sum file](https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs) included in the checked-out repository.
- This means that `actions/checkout` must be executed before `action/setup-go` is executed.
- The order of steps in the …
> fix the `Restore cache failed` warning of the ci.yaml github actions job

- README.md
- flags.go
- internal/encoding/dotenv/map_utils.go
- internal/encoding/ini/map_utils.go
- internal/encoding/javaproperties/map_utils.go
- logger.go
- viper_test.go
This PR corrects spelling mistakes in comments and docs.
> docs: fix typos in comments

- README.md
- remote/remote.go
- viper.go
This adds support for NATS as a remote configuration storage. This is the continuation of the crypt PR @sagikazarmark.
> Add NATS support

- viper_test.go
This PR removes usages of deprecated [io/ioutil](https://pkg.go.dev/io/ioutil) and simplifies tests by using [T.TempDir](https://pkg.go.dev/testing#T.TempDir).
> Remove usages of deprecated io/ioutil; simplify viper tests

- viper_go1_15.go
- viper_go1_16.go
- watch.go
- watch_unsupported.go
`// +build` is obsolete starting from Go 1.18.
https://pkg.go.dev/cmd/go#hdr-Build_constraints
> chore: remove deprecated build tags

- README.md
- internal/encoding/decoder.go
- internal/encoding/decoder_test.go
- internal/encoding/dotenv/codec.go
- internal/encoding/dotenv/codec_test.go
- internal/encoding/dotenv/map_utils.go
- internal/encoding/encoder.go
- internal/encoding/encoder_test.go
- internal/encoding/hcl/codec.go
- internal/encoding/hcl/codec_test.go
- internal/encoding/ini/codec.go
- internal/encoding/ini/codec_test.go
- internal/encoding/ini/map_utils.go
- internal/encoding/javaproperties/codec.go
- internal/encoding/javaproperties/codec_test.go
- internal/encoding/javaproperties/map_utils.go
- internal/encoding/json/codec.go
- internal/encoding/json/codec_test.go
- internal/encoding/toml/codec.go
- internal/encoding/toml/codec_test.go
- internal/encoding/yaml/codec.go
- internal/encoding/yaml/codec_test.go
- logger.go
- overrides_test.go
- util.go
- util_test.go
- viper.go
- viper_test.go
This PR refactors code and replaces `interface{}` with the alias `any`.
> refactor: replace 'interface{}' with 'any'

- flags_test.go
- overrides_test.go
- viper_test.go
This PR refactors tests:
- reverse actual and expected values in some asserts;
- replace `require.Nil(t, err)` with `require.NoError(t, err)`;
- simplifies slice comparison;
- replace `assert.Equal(t, 1, len(items))` with `assert.Len(t, items, 1)`;
- replace sorted slice comparing with `assert.ElementsMatch`;
- use `assert.Failf(...)` instead of `assert.Fail(fmt.Sprintf(...))`;
- use `assert.IsType(...)` instead of `assert.Equal(t, reflect.TypeOf(...)`.
> test: refactor asserts

- flags_test.go
- internal/encoding/decoder_test.go
- internal/encoding/dotenv/codec_test.go
- internal/encoding/encoder_test.go
- internal/encoding/hcl/codec_test.go
- internal/encoding/ini/codec_test.go
- internal/encoding/javaproperties/codec_test.go
- internal/encoding/json/codec_test.go
- internal/encoding/toml/codec_test.go
- internal/encoding/yaml/codec_test.go
- util_test.go
- viper_test.go
This PR refactors tests to use functions from the `testify` package instead of `if`s.
As a bonus, we can remove `//nolint:dupl` comments.
> test: replace ifs with asserts to simplify tests

- README.md
[viper does support multiple hosts](https://github.com/spf13/viper/blob/master/remote/remote.go#L79) for remote providers, but there is no info about it
> Add info about multiple hosts for remote config

- README.md
Even though it's kind of evident as these functions don't return an error, it can still come as a surprise.
> Note Get* behavior on parse failure

- .golangci.yaml
- file.go
- flags.go
- internal/encoding/dotenv/codec_test.go
- internal/encoding/dotenv/map_utils.go
- internal/encoding/hcl/codec_test.go
- internal/encoding/ini/codec_test.go
- internal/encoding/ini/map_utils.go
- internal/encoding/javaproperties/codec_test.go
- internal/encoding/javaproperties/map_utils.go
- internal/encoding/json/codec_test.go
- internal/encoding/toml/codec_test.go
- internal/encoding/yaml/codec_test.go
- overrides_test.go
- util.go
- viper.go
- viper_test.go
This PR enables `godot` linter. `godot` ensures comments always end with a full stop.
> fix: godot lint issues

- viper.go
- viper_test.go
The current `viper` implementation does not allow to `viper.Unmarshal` environment variables into structs without binding them first (using `viper.BindEnv`). This behavior results in an "empty" struct (i.e no values filled) if no configuration file is provided with matching keys.
This pull request adds a new `viper.BindStruct` function which takes a struct pointer and binds each (nested) struct field to an environment variable using the struct field's name or the user-specified `mapstructure` tag. The implementation is quite simple, since I could reuse some functions:
```go
func (v *Viper) BindStruct(input interface{}) error {
envKeysMap := map[string]interface{}{}
if err := mapstructure.Decode(input, &envKeysMap); err != nil {
return err
}
structKeys := …
```
> Implement viper.BindStruct for automatic unmarshalling from environment variables

- .github/workflows/ci.yaml
- flags_test.go
- viper_test.go
This PR extends `go test` with `-shuffle` [flag](https://pkg.go.dev/cmd/go#hdr-Testing_flags):
> ```
> -shuffle off,on,N
>     Randomize the execution order of tests and benchmarks.
>     It is off by default. If -shuffle is set to on, then it will seed
>     the randomizer using the system clock. If -shuffle is set to an
>     integer N, then N will be used as the seed value. In both cases,
>     the seed will be reported for reproducibility.
> ```
Also, fix conflicting tests.
> ci: enable test shuffle and fix tests

- viper.go
- viper_test.go
This is a follow-up PR after #1429. A [comment](https://github.com/spf13/viper/pull/1429#issuecomment-1843183656) mentioned `UnmarshalExact` not working as intended. Looking into the code I found that the list of struct keys was not merged with `AllKeys` inside `UnmarshalExact`, leading to the mentioned error.
This PR fixes this by performing the same steps in `UnmarshalExact`.
@sagikazarmark
> Merge missing struct keys inside UnmarshalExact

- README.md
- TROUBLESHOOTING.md
I noticed that the link to the Golang Modules documentation leads to a site that says
> The Go wiki on GitHub has moved to go.dev (#61940).
See: https://github.com/golang/go/wiki/Modules
This PR replaces the link in the README and TROUBLESHOOTING files with the one that's suggested on the old site.
> Update links to Golang Modules documentation

- README.md
- go.mod
- go.sum
- viper.go
- viper_test.go
Use the new fork of mapstructure
Fixes #1707
> chore: update mapstructure

- go.mod
- go.sum
- logger.go
- util.go
- util_test.go
- viper.go
Not necessary since minimum Go version is bumped to 1.21
Fixes #1664
> Drop slog shim

- .github/workflows/ci.yaml
- file.go
- file_finder.go
- finder.go
- finder_example_test.go
- finder_test.go
- go.mod
- go.sum
- viper.go
> Replace file searching API with a finder

- viper.go
- viper_test.go
Return an error from `ReadConfig` and `MergeConfig` when no config type is set.
Fixes #1784
> Fix missing config type when reading from a buffer

- experimental.go
- viper.go
- viper_test.go
> Add experimental flag for bind struct

- go.mod
- go.sum
Now that consul/api is gone from the module dependency tree, these dependencies can be reverted to their latest releases; the changes since then are only CI-related or documentation updates, which aren't relevant for downstream users.
(This is very minor but avoids questions like
https://github.com/kubernetes/kubernetes/pull/123339#discussion_r1618125911 about the use of untagged dependencies.)
> Revert to go-difflib and go-spew releases

- viper.go
- viper_test.go
Addresses https://github.com/spf13/viper/issues/871
Simply copies the `keyDelim` from the parent chart to the subchart when calling `viper.Sub()`. Since there's currently no way to change the `keyDelim` of a viper instance post-creation, this is the only way to ensure that the `sub` viper instance maintains the `keyDelim`.
> feat: copy keydelim from parent chart in viper.Sub()

- internal/encoding/json/codec_test.go
- viper_test.go
This PR fixes these issues reported by [testifylint](https://github.com/Antonboom/testifylint):
```
22:55 $ testifylint  --fix  ./...
/home/xx/viper/viper_test.go:1624:2: expected-actual: need to reverse actual and expected values
/home/xx/viper/viper_test.go:1923:2: encoded-compare: use assert.YAMLEq
/home/xx/viper/viper_test.go:480:2: require-error: for error assertions use require
/home/xx/viper/viper_test.go:2504:2: require-error: for error assertions use require
/home/xx/viper/internal/encoding/json/codec_test.go:62:2: encoded-compare: use assert.JSONEq
```
> Fix issues reported by testifylint

- viper.go
- viper_test.go
As described in the README, I expect viper to infer config type based on config file extension.
> viper.SetConfigType("yaml") // REQUIRED if the config file does not have the extension in the name
Since `1.20` this behavior seems broken.
If this is intended (or not working the way I think it should) let me know.
Fixes #1994
> fix(config): get config type from v.configType or config file ext

- UPGRADE.md
relates to https://github.com/spf13/viper/issues/1999
> Update update guide with `mapstructure` package replacement.

- viper.go
- viper_test.go
> Backport config type fixes to 1.20.x

- viper.go
- viper_test.go
This PR adds support for `pflag.BoolSlice`, `pflag.UintSlice` and `pflag.Float64Slice` (see failing test below).
Note: there are other pflag slices not supported, but this PR propose to add supports for at least one of each kind: Bool, Uint, & Float64.
Below is a simple failing test
```golang
func TestBindPFlagsSlices(t *testing.T) {
set := pflag.NewFlagSet("test", pflag.ContinueOnError)
set.IntSlice("intslice", []int{}, "")
set.BoolSlice("boolslice", []bool{}, "")
set.Float64Slice("float64slice", []float64{}, "")
set.UintSlice("uintslice", []uint{}, "")
v := New()
v.BindPFlags(set)
// Does not fail as effectively supported
set.Set("intslice", "1,2")
assert.Equal(t, []int{1, 2}, v.Get("intslice"))
// Fails as not supported
set.Set("boolslice", "true,false")
assert.Equal(t, []bool{true, …
```
> Add support for flags pflag.BoolSlice, pflag.UintSlice and pflag.Float64Slice

- util.go
In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.
> refactor: use the built-in max/min to simplify the code
