spf13/viper

- viper.go
> Added docstrings to all exported functions

- README.md
I realized that I did not document the new feature in the `README`
> Added doc entry on nested key access

- README.md
> Update README with info about supporting Java properties files

- README.md
doit has been moved and renamed to doctl
> Update Readme with doit's new location

- viper.go
- viper_test.go
#204 
Signed-off-by: Chuanjian Wang <me@ckeyer.com>
> add GetInt64

- flags_test.go
- util.go
- viper.go
- viper_test.go
I think, it is a little bit cleaner now
> Small refactorings

- viper.go
- viper_test.go
> Check for nil in viper.Sub

- viper.go
- viper_test.go
```
BenchmarkGetBool-4            1021          481           -52.89%
BenchmarkGet-4                879           403           -54.15%
BenchmarkGetBoolFromMap-4     6.56          6.40          -2.44%
benchmark                     old allocs     new allocs     delta
BenchmarkGetBool-4            6              4              -33.33%
BenchmarkGet-4                6              4              -33.33%
BenchmarkGetBoolFromMap-4     0              0              +0.00%
benchmark                     old bytes     new bytes     delta
BenchmarkGetBool-4            113           49            -56.64%
BenchmarkGet-4                112           48            -57.14%
BenchmarkGetBoolFromMap-4     0             0             +0.00%
```
Fixes #249
Fixes https://github.com/spf13/hugo/issues/2536
> Restore performance for the simple case

- remote/remote.go
- viper.go
> Revert "Avoid the start of go-routines which are never get stopped (Description Issue #312)"

- remote/remote.go
- viper.go
Removed dependency to crypto from viper.go
> Avoid the start of go-routines which are never get stopped (Description Issue #312; ) Follow Up on Pull-Request #313

- README.md
> Fix apostrophes in README

- .travis.yml
- flags_test.go
- remote/remote.go
- util_test.go
- viper.go
* Run gofmt on all existing code
* Add check to .travis.yml that verifies that all code is gofmt-compliant
* Touch up some newlines
> gofmt code

- viper.go
> correct a comment on viper.Set()

- README.md
A simple readme addition to getting started with Consul remote provider
> Add README.md for Consul remote provider

- README.md
After running through the readme, I needed the functionality. After digging, seems it's been there since 2k16, but no docs were provided. Decided it might help others as well.
This should also help to close https://github.com/spf13/viper/issues/33.
@spf13 Looking forward to feedback.
> Add WriteConfig documentation

- README.md
1. Add installation method in the readme page.
Please review my code.
Best,
Alpha
> ADD: installation method

- README.md
> Improve Unmarshal docs

- viper.go
Fix issue https://github.com/spf13/viper/issues/622
> Add missing call to initWG.Done() in WatchConfig()

- viper.go
- viper_test.go
Added error handling around ineffectual err assignments. Please review
thoroughly.
> Add error handling

- viper.go
- viper_test.go
Removed unnecessary conversions.
> Simplify code

- viper.go
Simple optimisation to reduce memory allocations and copying(while appending).
> Added capacity to slice creation

- README.md
[Mercure](https://github.com/dunglas/mercure) uses Viper too!
> Add Mercure in the list of projects using Viper

- .gitignore
- .golangci.yml
- .idea/externalDependencies.xml
- .idea/go.imports.xml
- .idea/modules.xml
- .idea/runConfigurations/Check.xml
- .idea/runConfigurations/Lint.xml
- .idea/runConfigurations/Tests.xml
- .idea/viper.iml
- Makefile
> Improve tooling

- README.md
- viper.go
- viper_test.go
Fixes #569
Fixes #575
Fixes #624
> Add string replacer interface and env key replacer option

- viper.go
> Add decoder opts to unmarshal exact

- viper.go
> Add log for remote config errors

- go.mod
- go.sum
- viper_test.go
> update mapstructure dependency

- README.md
> docs: add run on repl.it badge with example

- README.md
- viper.go
Updates https://github.com/spf13/viper/issues/268
> Document that vipers are not safe for concurrent reads and writes

- viper.go
> Add ini load options argument

- viper.go
- viper_test.go
This PR fixes #246 and adds tests to changes from #398.
Please, consider it to merge!
Fixes #246
Fixes #398
> Add a proper processing for pflag.StringArray

- .github/workflows/ci.yml
- .github/workflows/wasm.yml
> ci: run builds on Go 1.17

- go.mod
- go.sum
> Update go-ini dependency

- README.md
> docs: fix indentation in code samples

- viper.go
Fixes #913
Needed to resubmit to fix a conflict
> Resubmit #913

- .github/workflows/feedback_issue.yml
- .github/workflows/feedback_pull_request.yml
> ci: fix github script

- logger.go
- util.go
- util_test.go
- viper.go
- viper_go1_15.go
> Add new logger interface

- experimental_logger.go
Expose the logger interface as an experimental feature as per #1268
Finalizing the logger interface is tracked in #1270
> Experimental logger

- .github/workflows/ci.yml
- .golangci.yml
- Makefile
- viper.go
> chore: add go 1.18 builds

- .github/ISSUE_TEMPLATE/feature_request.yaml
- .github/release.yml
- .github/workflows/checks.yaml
> add release note configuration

- watch_unsupported.go
Fixes #538 
See https://github.com/fsnotify/fsnotify/commit/7ed195facfcd33fc8a54c731565fbbe1f959edd6
> Disable watch on appengine

- README.md
I think this "manifesto" of sorts was mostly before my time as a software engineer, so I personally had no idea what it was referring to.
> Provide a link to explain what a 12-factor app is

- README.md
Adds Meshery to the list of Go projects using Viper
> ADD Meshery to projects

- README.md
[Bearer](https://github.com/bearer/bearer) uses Viper :)
> doc: add bearer/bearer as projects using Viper

- README.md
> docs: Coder uses Viper

- viper.go
- viper_test.go
Support for pflag's StringToString was added long back, but Viper Still couldn't bind to pflag StringToInt. Addid that support.
>  extend v.find() to handle stringToInt value types with stringToInt pflag #1435 

- viper.go
> feat: add func GetEnvPrefix

- README.md
This PR adds Vitess to the list of projects that are using Viper
> Add Vitess to list of projects using Viper

- Makefile
Diving into viper development environment, I hit some rough edges. Here are some fixes for this.
> Make deps fixes

- .github/workflows/ci.yaml
- internal/features/bind_struct.go
- internal/features/bind_struct_default.go
- viper.go
- viper_test.go
> fix!: hide struct binding behind a feature flag

- viper.go
- viper_test.go
Updated all viper_test* to use local viper instance 
Fixes: #1700
> fix #1700: update tests to use local viper instance

- README.md
- viper.go
Since https://github.com/spf13/viper/pull/1218 crypt is provided by https://github.com/sagikazarmark/crypt
> Update references to bketelsen/crypt

- remote.go
- viper.go
> refactor: move remote code to separate file

- README.md
- viper.go
> Allow setting options on the global Viper instance

- viper.go
- viper_test.go
Allow setting a custom, default decode hook.
Fixes #1606
> Add decoder hook option

- remote.go
- util.go
- viper.go
> Encoder improvements

- .github/workflows/checks.yaml
- .github/workflows/ci.yaml
- .github/workflows/stale.yaml
> ci: restrict permissions to the required ones
